### ISSUE TITLE
Update config.guess in sublibraries

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA-Baselibs#104]
Testing on AWS Graviton3 showed that many of the `config.guess` files in Baselibs sublibraries are quite old and need updating. 

Per testing:

```
> ##   Then due to the age of some config.guess files in the sub-libraries, I had to do:
> ##      cp config.guess antlr2/scripts/config.guess
> ##      cp config.guess gsl-2.7/config.guess
> ##      cp config.guess szlib/bin/config.guess
> ##      cp config.guess hdf4/bin/config.guess
> ##      cp config.guess hdf5/bin/config.guess
> ##      cp config.guess netcdf-cxx4/config.guess
> ##      cp config.guess nccmp/config.guess
> ##      cp config.guess hdf-eos2-3.0/config/config.guess
> ##      cp config.guess hdf-eos5-2.0/config/config.guess
> ##      cp config.guess TOOLKIT/config/config.guess
```

Now, I'm not the autotools expert like some so maybe I'll invoke the name of @WardF or @DennisHeimbigner here as they are the autotools gurus of netCDF and ask:

Should I just instead run `autoreconf -f -v -i` instead in these libraries if they are using autotools? Perhaps that is the "right" way to get a good `config.guess` when building on a new machine.

**Comment by mathomp4** [comment]
The new `config.guess` got in in #93

**Comment by WardF** [comment]
So `config.guess` is a generated file, and best practice is to not include `autoconf`-related generated files in version control, unless it's part of a release.   `config.guess` is generated by `autoreconf -ifv`, as you point out.  I think running `autoreconf -ifv` in these library folders prior to building would be the correct thing to do.  It certainly shouldn't hurt anything (I'm 99.9% sure).  TBH, I often run `autoreconf` as part of my scripts, because there are old tarballs I download and run as part of a scripted process, and the included `configure` fails unless I regenerate it.

**Comment by WardF** [comment]
I'm unfamiliar with the "recipe" used to generate `config.guess`; I'm unsure if it is a static file copied into a project when `autoreconf` is run, or if it is derived from the specific `configure.ac`.  If it's the latter, there's a chance that the `config.guess` generated at the top level may not do what is needed for the subprojects.
