### ISSUE TITLE
Add Support for NVHPC

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA-Baselibs#32]
I'm going to use this as an omnibus issue to track support for NVHPC in Baselibs. 

One issue was HDF5 could not build. A workaround for this was to build Open MPI without zlib support (as it was having issues with the zlib in Baselibs). So the current modules being used to build on Discover are:

```
comp/gcc/10.3.0
comp/nvhpc/21.5-nompi
other/localrc/nvhpc-21.5/gcc-10.3.0
mpi/openmpi/4.0.6/nvhpc-21.5-carl-nozlib
```

Current libraries with issues:

- CDO
- ESMF
- GFE 
- FLAP → Fixed with new FLAP version (see #33)
- SDPToolkit → Turned off for NVHPC (see #33)

cc: @tclune @cponder

**Comment by mathomp4** [comment]
At the moment, CDO and ESMF have the same issue. When trying to build both throw:
```
"/usr/local/other/gcc/10.3.0/include/c++/10.3.0/bits/atomic_base.h", line 236: error: identifier "__GCC_ATOMIC_TEST_AND_SET_TRUEVAL" is undefined
      { return __i ? __GCC_ATOMIC_TEST_AND_SET_TRUEVAL : 0; }
```
This might be solvable by a siterc update:

https://forums.developer.nvidia.com/t/support-for-atomic-in-libstdc-missing/135403/2

but that's above me.

**Comment by mathomp4** [comment]
FLAP will be fixed by moving to tag `geos/v1.10.0`.

SDPToolkit's erro is...weird. And honestly, I don't care about that library, so I'm going to work on making a GNUmakefile hack to just "turn off building" when PGI/NVHPC.

**Comment by mathomp4** [comment]
Note: I believe @tclune and @cponder are working on the GFE updates. Might be a combination of updates to the libraries themselves and updates to the compiler.

**Comment by tclune** [comment]
Carl says that the upcoming compiler can build gFTL-shared with NVHPC without changes, so there will not be a release do to that.  (There is an unrelated minor bugfix in gFTL that does not affect GEOS that will probably result in a patch in the near future.)

However, the NVHPC branch will be essential for testing MAPL if ESMF can be ported.   So it depends on when we get access to the next compiler.  If that is before ESMF is ported, we can delete the nvhpc branches.  Otherwise we'll want a temporary baselibs based on those so that we can expose issues with MAPL in the mean time.
